import type {State} from './types'
import {dateKey} from './domain'
export function demoState():State {
 const now=Date.now(),today=dateKey(),meta={createdAt:new Date(now).toISOString(),updatedAt:new Date(now).toISOString()}
 const b={primary:{usedPercent:28,windowDurationMins:300,resetsAt:Math.floor(now/1000)+9655},secondary:{usedPercent:42,windowDurationMins:10080,resetsAt:Math.floor(now/1000)+322500}}
 return {
  accounts:[{...meta,id:'demo-a1',name:'DeepSeek API',provider:'DeepSeek',type:'api',currency:'CNY',balance:83.42,total:100,resetsAt:null,note:'演示余额',source:'manual',threshold:10},{...meta,id:'demo-a2',name:'OpenAI API 预算',provider:'OpenAI',type:'api',currency:'USD',balance:24.8,total:30,resetsAt:null,note:'手动预算示例',source:'manual',threshold:5},{...meta,id:'demo-a3',name:'Claude 订阅',provider:'Claude',type:'subscription',currency:'percent',balance:86,total:100,resetsAt:new Date(now+86400000).toISOString(),note:'演示额度',source:'manual',threshold:20}],
  tasks:[{...meta,id:'demo-t1',title:'高等数学 · 第三章习题',course:'高等数学',type:'assignment',dueAt:new Date(now+6*3600000).toISOString(),status:'pending',url:'',note:'演示任务',source:'manual'},{...meta,id:'demo-t2',title:'大学英语 · 单元测试',course:'大学英语',type:'exam',dueAt:new Date(now+2*86400000).toISOString(),status:'pending',url:'',note:'',source:'manual'},{...meta,id:'demo-t3',title:'计算机基础实验报告',course:'计算机基础',type:'assignment',dueAt:new Date(now+4*86400000).toISOString(),status:'completed',url:'',note:'',source:'manual'}],
  watchlist:[{...meta,id:'demo-w1',symbol:'AAPL',name:'苹果',market:'US',targetAbove:null,targetBelow:null},{...meta,id:'demo-w2',symbol:'NVDA',name:'英伟达',market:'US',targetAbove:null,targetBelow:null},{...meta,id:'demo-w3',symbol:'600519.SH',name:'贵州茅台',market:'CN',targetAbove:null,targetBelow:null}],
  quotes:[{symbol:'AAPL',market:'US',name:'苹果',price:228.5,changePercent:1.24,volume:31500000,currency:'USD',asOf:new Date(now).toISOString(),receivedAt:new Date(now).toISOString(),source:'演示数据',latency:'delayed',session:'演示'},{symbol:'NVDA',market:'US',price:132.18,changePercent:-0.86,volume:80200000,currency:'USD',asOf:new Date(now).toISOString(),receivedAt:new Date(now).toISOString(),source:'演示数据',latency:'delayed',session:'演示'},{symbol:'600519.SH',market:'CN',price:1466.3,changePercent:0.52,volume:2710000,currency:'CNY',asOf:new Date(now).toISOString(),receivedAt:new Date(now).toISOString(),source:'演示数据',latency:'minute',session:'演示'}],
  goals:[{...meta,id:'demo-g1',exam:'postgraduate',title:'考研 · 稳步前进',targetDate:new Date(now+80*86400000).toISOString(),subjects:['数学','英语','政治'],dailyMinutes:180},{...meta,id:'demo-g2',exam:'cet6',title:'英语六级 · 目标 550',targetDate:new Date(now+70*86400000).toISOString(),subjects:['英语六级'],dailyMinutes:60}],
  studyPlans:[{...meta,id:'demo-p1',title:'复习一元函数微分学',subject:'数学',date:today,status:'completed',minutes:60},{...meta,id:'demo-p2',title:'精读一篇英语六级阅读',subject:'英语',date:today,status:'pending',minutes:30},{...meta,id:'demo-p3',title:'整理政治知识点',subject:'政治',date:today,status:'pending',minutes:45}],
  studySessions:[...Array.from({length:7},(_,i)=>({...meta,id:`demo-s${i}`,subject:'数学',minutes:[90,120,75,150,110,130,95][i],date:dateKey(new Date(now-(6-i)*86400000))}))],mistakes:[],chatMessages:[],alerts:[],demands:[],consultations:[],
  codex:{status:'ok',syncedAt:new Date(now).toISOString(),rateLimits:b,rateLimitsByLimitId:{codex:b},dailyUsageBuckets:Array.from({length:7},(_,i)=>({startDate:dateKey(new Date(now-(6-i)*86400000)),tokens:[18000,29000,14000,36000,24000,42000,26500][i]})),history:Array.from({length:12},(_,i)=>({observedAt:new Date(now-(11-i)*3600000).toISOString(),rateLimits:{primary:{...b.primary,usedPercent:[5,8,16,22,4,9,12,18,21,24,26,28][i]},secondary:{...b.secondary,usedPercent:30+i}}}))},
  settings:{profile:{name:'学习者',timezone:'Asia/Shanghai'},ai:{provider:'deepseek',baseUrl:'https://api.deepseek.com',model:'deepseek-chat',keyConfigured:false,dailyRequestLimit:50,maxTokens:2048,inputPrice:0,outputPrice:0,currency:'CNY'},deepseek:{keyConfigured:false},openai:{keyConfigured:false},market:{usProvider:'alpaca',alpacaFeed:'iex',alpacaKeyConfigured:false,alpacaSecretConfigured:false,tushareKeyConfigured:false,refreshSeconds:60},notifications:{quotaBelow:20,balanceBelow:10,taskHours:24},agent:{tokenConfigured:false,lastSeen:null}},sync:{connected:true,lastSeen:new Date(now).toISOString()}
 }
}
