import {useRef,useState,type FormEvent} from 'react'
import {MessageSquare,ShieldCheck,ExternalLink,FlaskConical,Plus,LoaderCircle} from 'lucide-react'
import {useWorkbench} from '../lib/store'
import {dateTime,money} from '../lib/domain'
import {categoryLabels,sourceLabels,statusLabels,filterDemands,evaluateDemands,parseDemandImport,syntheticDemands,type DemandFilters} from '../lib/demands'
import type {Demand,DemandCategory,Consultation} from '../lib/types'
import {Panel,Button,Badge,SectionTitle,Modal,Empty} from '../components/common'

const categories=Object.entries(categoryLabels)
const consultationStatuses={new:'待处理',answered:'已答复',closed:'已关闭'}
const roogooFaq='https://help.roogoo.com/zh-CN/articles/11659674-roogoo-card-%E7%A4%BE%E5%8C%BA%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98-%E7%94%A8%E5%8D%A1%E6%8C%87%E5%8D%97'
const importExample=JSON.stringify([{text:'【合成示例】订阅付款失败，想了解官方排查建议。',source:'sample',sourceUrl:'',expectedCategory:'payment_failure'}],null,2)
type Run=(operation:()=>Promise<unknown>)=>Promise<boolean>

function CategoryOptions(){return <>{categories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</>}

function DemandForm({record,run,onClose,disabled}:{record:Demand|null;run:Run;onClose:()=>void;disabled:boolean}){
 const {save}=useWorkbench()
 const [text,setText]=useState(record?.text??''),[source,setSource]=useState<Demand['source']>(record?.source??'manual'),[url,setUrl]=useState(record?.sourceUrl??''),[expected,setExpected]=useState<DemandCategory|''>(record?.expectedCategory??''),[confirmed,setConfirmed]=useState(record?.rightsConfirmed??false)
 async function submit(e:FormEvent){e.preventDefault();if(await run(async()=>{const [input]=parseDemandImport(JSON.stringify([{text,source,sourceUrl:url,expectedCategory:expected||null,status:record?.status??'pending'}]),confirmed);await save('demands',input,record?.id)}))onClose()}
 return <form onSubmit={submit} className="demand-form"><label className="field"><span>去标识化原文 *</span><textarea required maxLength={4000} rows={6} value={text} onChange={e=>setText(e.target.value)} placeholder="仅录入你有权使用的提问，不包含姓名、联系方式、账号或银行卡信息"/><small>{text.length} / 4000 字</small></label><div className="form-grid"><label className="field"><span>内容来源 *</span><select value={source} onChange={e=>setSource(e.target.value as Demand['source'])}>{Object.entries(sourceLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="field"><span>人工参考类别（选填）</span><select value={expected} onChange={e=>setExpected(e.target.value as DemandCategory|'')}><option value="">未标注</option><CategoryOptions/></select></label></div><label className="field"><span>来源链接（选填）</span><input type="url" maxLength={2000} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/post"/><small>仅接受无账号密码、无查询参数的 HTTP/HTTPS 链接，系统不访问链接。</small></label><label className="demand-consent"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>我确认有权使用原文，已删除联系及身份信息；自愿提供的内容已获得对方同意。</span></label>{record&&<p className="helper-text">编辑原文或来源链接会清除已有分析，需要重新点击 AI 分析。</p>}<div className="dialog-footer"><Button type="button" variant="outline" disabled={disabled} onClick={onClose}>取消</Button><Button type="submit" disabled={disabled}>保存原文</Button></div></form>
}

function ConsultationForm({record,run,onClose,disabled}:{record:Consultation|null;run:Run;onClose:()=>void;disabled:boolean}){
 const {save}=useWorkbench()
 const [question,setQuestion]=useState(record?.question??''),[alias,setAlias]=useState(record?.alias??''),[note,setNote]=useState(record?.note??''),[status,setStatus]=useState<Consultation['status']>(record?.status??'new'),[consent,setConsent]=useState(record?.consentConfirmed??false)
 return <form className="demand-form" onSubmit={async e=>{e.preventDefault();if(await run(async()=>{if(!consent)throw new Error('请确认问题由对方自愿提出并同意记录');await save('consultations',{question,alias,note,status,consentConfirmed:true},record?.id)}))onClose()}}><label className="field"><span>自愿提出的问题 *</span><textarea required maxLength={4000} rows={5} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="记录对方自愿提出的具体问题，并去除个人信息"/></label><div className="form-grid"><label className="field"><span>匿名代称（选填）</span><input maxLength={80} value={alias} onChange={e=>setAlias(e.target.value)} placeholder="自定义代称，不填实名或账号"/></label><label className="field"><span>处理状态</span><select value={status} onChange={e=>setStatus(e.target.value as Consultation['status'])}>{Object.entries(consultationStatuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label className="field"><span>处理备注（选填）</span><textarea rows={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="记录已核实的信息与后续处理，不填联系方式"/></label><label className="demand-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>对方自愿提出问题并同意记录；这些文字已去标识化，不包含联系或身份信息。</span></label><div className="dialog-footer"><Button type="button" variant="outline" onClick={onClose} disabled={disabled}>取消</Button><Button type="submit" disabled={disabled}>保存咨询</Button></div></form>
}

export default function Demands(){
 const {state,demo,busy,action,save,remove,notify,setPage}=useWorkbench()
 const [tab,setTab]=useState<'analysis'|'consultations'|'guide'>('analysis'),[pending,setPending]=useState(false),[error,setError]=useState('')
 const locked=useRef(false)
 const [filters,setFilters]=useState<DemandFilters>({search:'',category:'all',status:'all'}),[importText,setImportText]=useState(importExample),[rights,setRights]=useState(false),[importResult,setImportResult]=useState<{imported:number;duplicates:number;records:Demand[]}|null>(null)
 const [editor,setEditor]=useState<{kind:'demand';record:Demand|null}|{kind:'consultation';record:Consultation|null}|null>(null),[deleting,setDeleting]=useState<{collection:'demands'|'consultations';id:string;text:string}|null>(null)
 const run:Run=async operation=>{if(locked.current||demo||busy)return false;locked.current=true;setPending(true);setError('');try{await operation();return true}catch(e){const message=e instanceof Error?e.message:'请求失败，请稍后重试';setError(message);notify(message,'error');return false}finally{locked.current=false;setPending(false)}}
 if(!state)return <div className="page-loading">正在读取需求与咨询…</div>
 const disabled=pending||demo||busy,records=filterDemands(state.demands,filters),evaluation=evaluateDemands(state.demands)
 let syntax=''
 try{const items=parseDemandImport(importText,true);syntax=`格式有效：${items.length} 条，提交时仍由服务器验证授权、隐私和重复记录。`}catch(e){syntax=(e as Error).message}
 const syntaxValid=syntax.startsWith('格式有效')
 const importItems=async(items:ReturnType<typeof parseDemandImport>)=>{const result=await action<{imported:number;duplicates:number;records:Demand[]}>('/demands/import',{items});setImportResult(result);notify(`新增 ${result.imported} 条，重复 ${result.duplicates} 条`)}
 return <div className="page-enter demands-page"><SectionTitle eyebrow="原文 · 分析 · 人工审核" title="需求与咨询" description="导入有权使用的原文，核对 AI 建议，再记录自愿提出的咨询。"/>
 <div className="demand-intro"><div><ShieldCheck size={19}/><div><strong>小黑盒读取：待授权评估</strong><p>当前没有自动采集、评论、私信或发帖。先使用去标识化文字验证流程。</p></div></div><ol className="demand-steps"><li>导入原文</li><li>点击 AI 分析</li><li>人工审核</li><li>自愿咨询</li></ol></div>
 <p className="demand-limit">与学习助手共用每日 {state.settings.ai.dailyRequestLimit} 次请求上限{state.settings.ai.dailyBudget!=null?`及 ${money(state.settings.ai.dailyBudget,state.settings.ai.currency)} 估算费用阈值`:''}。费用阈值是先前调用的估算，单次生成或未知用量可能超出。<button className="text-button" onClick={()=>setPage('settings')}>设置 AI</button></p>
 {demo&&<div className="info-note">演示模式仅供浏览；需求和咨询为空。退出演示并登录后可明确选择导入合成示例。</div>}
 <nav className="segmented demand-tabs" aria-label="需求与咨询分区">{([['analysis','需求分析'],['consultations','自愿咨询'],['guide','使用说明']] as const).map(([value,label])=><button key={value} className={tab===value?'selected':''} aria-pressed={tab===value} aria-controls={`demand-${value}`} onClick={()=>setTab(value)}>{label}</button>)}</nav>
 {error&&<div className="form-error" role="alert">{error}</div>}
 {pending&&<p className="demand-pending" role="status"><LoaderCircle className="spin" size={16}/>正在处理，请勿重复提交。AI 分析可能需要约 45 秒。</p>}
 {tab==='analysis'&&<section id="demand-analysis" aria-label="需求分析"><div className="demand-layout"><Panel title="录入与导入" description="单条最多 4000 字；JSON 每批 1–20 条" action={<Button disabled={disabled} onClick={()=>{setError('');setEditor({kind:'demand',record:null})}}><Plus size={15}/>录入原文</Button>}><details className="demand-import" open><summary>批量 JSON 导入</summary><label className="field"><span>可编辑 JSON 数组</span><textarea rows={9} value={importText} onChange={e=>setImportText(e.target.value)} spellCheck={false} aria-describedby="demand-json-feedback"/></label><p id="demand-json-feedback" className={`helper-text ${syntaxValid?'':'negative'}`} role="status">{syntax}</p><label className="demand-consent"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/><span>我确认有权使用这批文字，已去除个人信息；自愿内容已获得同意。</span></label><div className="demand-actions"><Button disabled={disabled||!rights||!syntaxValid} onClick={()=>void run(async()=>importItems(parseDemandImport(importText,rights)))}>导入 JSON</Button><Button variant="outline" disabled={disabled} onClick={()=>setImportText(importExample)}>填入 JSON 示例</Button></div></details><div className="demand-samples"><FlaskConical size={18}/><p>四条合成示例，包含问题、已经解决、无关与广告，附人工参考类别。不是实际客户，也不会自动分析。</p><Button variant="outline" disabled={disabled} onClick={()=>void run(()=>importItems(syntheticDemands))}>导入 4 条合成示例</Button></div>{importResult&&<div className="demand-import-result" role="status"><strong>新增 {importResult.imported} 条 · 重复 {importResult.duplicates} 条</strong><p>重复项复用已有记录。返回 {importResult.records.length} 条记录引用。</p><details><summary>查看服务器返回的记录</summary><ul>{importResult.records.map((r,i)=><li key={`${r.id}-${i}`}>{r.text.slice(0,90)} <small>记录 {r.id}</small></li>)}</ul></details></div>}</Panel>
 <Panel title="人工标签验证" description="对全部记录统计，不受列表筛选影响"><div className="demand-agreement"><strong>{evaluation.agreement===null?'—':`${Math.round(evaluation.agreement*100)}%`}</strong><span>类别一致率</span></div><p className="body-copy">一致 {evaluation.agreed} / {evaluation.total} 条已分析且有参考类别的样本</p><p className="helper-text">已标注 {evaluation.labelled} 条 · 已分析 {evaluation.analyzed} 条。没有参考类别或还未分析的记录不进入分母。这个小样本结果不代表真实获客准确率。</p><div className="demand-models"><strong>结果来源</strong><p>{evaluation.models.length?evaluation.models.join('、'):'暂无可评估的模型结果'}</p><p>参考类别由你手动选择；合成示例的参考类别已预填。当前配置模型：{state.settings.ai.model}。</p></div></Panel></div>
 <Panel title={`原文与审核 · ${records.length} / ${state.demands.length}`} description="AI 结论仅供参考；人工通过也不会发送回复"><div className="demand-filters"><label className="field"><span>搜索原文或链接</span><input type="search" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="搜索原文关键词…"/></label><label className="field"><span>AI 类别</span><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value as DemandFilters['category']})}><option value="all">全部类别</option><option value="unanalyzed">未分析</option><CategoryOptions/></select></label><label className="field"><span>人工审核状态</span><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value as DemandFilters['status']})}><option value="all">全部状态</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
 {records.length?<div className="demand-records">{records.map(r=><article key={r.id} className="demand-record"><div className="demand-record-head"><div className="demand-badges"><Badge variant="outline" className={r.source==='sample'?'badge-amber':'badge-muted'}>{sourceLabels[r.source]}</Badge><Badge variant="outline" className={r.status==='approved'?'badge-green':'badge-muted'}>{statusLabels[r.status]}</Badge>{r.analysis&&<Badge variant="outline" className="badge-blue">AI：{categoryLabels[r.analysis.category]}</Badge>}</div><small>{dateTime(r.createdAt)}</small></div><h3>原文</h3><blockquote className="demand-original">{r.text}</blockquote>{r.sourceUrl&&<a className="demand-source" href={r.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink size={14}/>来源链接：{r.sourceUrl}</a>}
 {r.analysis?<div className="demand-analysis"><h3>AI 分析建议</h3><p>{r.analysis.summary}</p><p><strong>判断理由：</strong>{r.analysis.reason}</p><div className="demand-evidence"><strong>原文证据（逐字引用）</strong>{r.analysis.evidence.map((e,i)=><blockquote key={i}>{e}</blockquote>)}</div><small>模型自评置信度 {Math.round(r.analysis.confidence*100)}%，是建议强度，不是经验证的正确概率。</small><div className="demand-draft"><strong>回复草稿 · 未发送</strong><p>{r.analysis.draftReply||'模型未生成回复草稿。'}</p></div><p className="demand-meta">模型 {r.analysis.model} · {dateTime(r.analysis.analyzedAt)}{r.analysis.tokens===undefined?' · 用量未返回':` · ${r.analysis.tokens} 词元`}{r.analysis.cost===undefined?' · 费用未知':` · 估算 ${money(r.analysis.cost,r.analysis.currency??state.settings.ai.currency)}`}</p></div>:<p className="helper-text">尚未分析。点击下面的按钮才会调用当前 AI 接口。</p>}
 <label className="field demand-reference"><span>人工参考类别（用于验证）</span><select disabled={disabled} value={r.expectedCategory??''} onChange={e=>{const expectedCategory=e.target.value||null;void run(()=>save('demands',{expectedCategory},r.id))}}><option value="">未标注</option><CategoryOptions/></select></label><div className="demand-actions"><Button disabled={disabled} onClick={()=>void run(async()=>{await action(`/demands/${r.id}/analyze`,{});notify('分析已保存，请核对原文与证据')})}>{r.analysis?'重新 AI 分析':'AI 分析'}</Button><Button variant="outline" disabled={disabled||r.status==='approved'} onClick={()=>void run(()=>save('demands',{status:'approved'},r.id))}>人工通过</Button><Button variant="outline" disabled={disabled||r.status==='dismissed'} onClick={()=>void run(()=>save('demands',{status:'dismissed'},r.id))}>忽略</Button>{r.status!=='pending'&&<Button variant="ghost" disabled={disabled} onClick={()=>void run(()=>save('demands',{status:'pending'},r.id))}>恢复待审核</Button>}<Button variant="ghost" disabled={disabled} onClick={()=>{setError('');setEditor({kind:'demand',record:r})}}>编辑原文</Button><Button variant="ghost" disabled={disabled} onClick={()=>setDeleting({collection:'demands',id:r.id,text:r.text})}>删除</Button></div></article>)}</div>:<Empty icon={MessageSquare} title={state.demands.length?'没有匹配的记录':'还没有需求记录'} description={state.demands.length?'调整搜索、类别或状态，查看其他原文。':'录入有权使用的原文，或明确点击导入合成示例验证流程。'}/>}</Panel></section>}
 {tab==='consultations'&&<section id="demand-consultations" aria-label="自愿咨询"><Panel title={`自愿咨询 · ${state.consultations.length}`} description="只记录对方自愿提出并同意记录的问题，使用匿名代称，不收集联系方式" action={<Button disabled={disabled} onClick={()=>{setError('');setEditor({kind:'consultation',record:null})}}><Plus size={15}/>记录咨询</Button>}>{state.consultations.length?<div className="demand-records">{state.consultations.map(r=><article className="demand-record" key={r.id}><div className="demand-record-head"><strong>{r.alias||'匿名咨询'}</strong><Badge variant="outline">{consultationStatuses[r.status]}</Badge></div><p className="demand-original">{r.question}</p>{r.note&&<p className="demand-original"><strong>处理备注：</strong>{r.note}</p>}<p className="helper-text">自愿与同意已确认 · {dateTime(r.createdAt)}</p><div className="demand-actions"><Button variant="outline" disabled={disabled} onClick={()=>{setError('');setEditor({kind:'consultation',record:r})}}>编辑问题、备注与状态</Button><Button variant="ghost" disabled={disabled} onClick={()=>setDeleting({collection:'consultations',id:r.id,text:r.question})}>删除</Button></div></article>)}</div>:<Empty icon={MessageSquare} title="还没有自愿咨询" description="对方主动提出问题并同意记录后，再录入去标识化内容。"/>}</Panel></section>}
 {tab==='guide'&&<section id="demand-guide" aria-label="使用说明"><div className="demand-guide"><Panel title="先验证，再决定如何回应" description="四条示例仅用于检查流程与分类"><ol><li>录入或导入有权使用的去标识化原文。</li><li>先选择人工参考类别，再点击 AI 分析。导入与浏览不会自动消耗 AI 请求。</li><li>核对类别、理由与原文证据，选择人工通过或忽略。所有生成回复都是未发送草稿。</li><li>仅在对方自愿提出问题并同意记录时，手动记录咨询与处理状态。</li></ol><p>建议进一步验证 10–20 条经授权、已去标识化的真实问题，重点查看“已经解决”“不需要”和“广告”是否被误判。</p></Panel><Panel title="隐私与来源" description="授权与去标识化由录入者确认"><p>提交前删除姓名、账号、邮箱、手机号、银行卡号和其他身份或联系信息。服务器会拒绝明显邮箱、大陆手机号和银行卡号，但检测并不覆盖所有个人信息。</p><p>来源链接只允许无账号密码、无查询参数的 HTTP/HTTPS 地址，系统不访问链接。相同规范化原文与链接会复用已有记录。</p><p>编辑原文或链接会清除旧分析；分析期间修改内容，服务器会拒绝保存过时答案。需求与咨询经现有账号保存，可在设置中备份。</p></Panel><Panel title="教程来源与事实审核" description="仅供私人核查，不自动发布推广"><p><a href={roogooFaq} target="_blank" rel="noreferrer">Roogoo 官方 FAQ <ExternalLink size={14}/></a>说明预付卡和 USDT 充值，并提示订阅可能失败，不能保证订阅成功。</p><p>不同卡种的费用和支持范围以当时官方页面为准。免费教程不等于办卡或支付无费用；这些资料不构成订阅成功或产品兼容承诺。</p><p>这一版未提供开户、支付或地区限制绕过步骤；回应前请核对官方条件和真实需求。</p><p>筛选与可审查原文的思路参考 <a href="https://github.com/obris-dev/openmagpie" target="_blank" rel="noreferrer">OpenMagpie</a>。当前没有接入自动采集或对外发送。</p></Panel></div></section>}
 <Modal open={!!editor} onClose={()=>{if(!pending){setEditor(null);setError('')}}} title={editor?.kind==='demand'?(editor.record?'编辑需求原文':'录入需求原文'):(editor?.record?'编辑自愿咨询':'记录自愿咨询')} description="只保存经授权且已去标识化的内容。">{error&&<div className="form-error" role="alert">{error}</div>}{editor?.kind==='demand'?<DemandForm key={editor.record?.id??'new'} record={editor.record} run={run} onClose={()=>setEditor(null)} disabled={disabled}/>:editor&&<ConsultationForm key={editor.record?.id??'new'} record={editor.record} run={run} onClose={()=>setEditor(null)} disabled={disabled}/>}</Modal>
 <Modal open={!!deleting} onClose={()=>{if(!pending)setDeleting(null)}} title="删除这条记录？" description="记录将从工作台中移除，删除不会撤回或发送任何外部消息。"><p className="demand-original">{deleting?.text.slice(0,180)}</p>{error&&<div className="form-error" role="alert">{error}</div>}<div className="dialog-footer"><Button variant="outline" disabled={disabled} onClick={()=>setDeleting(null)}>保留记录</Button><Button variant="destructive" disabled={disabled} onClick={()=>{if(deleting)void run(()=>remove(deleting.collection,deleting.id)).then(ok=>{if(ok)setDeleting(null)})}}>确认删除</Button></div></Modal>
 </div>
}
