import {useState} from 'react'
import {Plus,RefreshCw,TrendingUp,Info,Clock,ArrowUpRight,Activity} from 'lucide-react'
import {ResponsiveContainer,AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip} from 'recharts'
import {useWorkbench} from '../lib/store'
import {money,dateTime,compact} from '../lib/domain'
import {Panel,Button,Badge,SectionTitle,Empty,RecordEditor,EditButton,DeleteButton,BusyButton,type Field} from '../components/common'
import type {Watch} from '../lib/types'
const fields:Field[]=[{key:'market',label:'市场',type:'select',default:'US',options:[{value:'US',label:'美股'},{value:'CN',label:'中国 A 股'}]},{key:'symbol',label:'股票代码',required:true,placeholder:'AAPL 或 600519.SH'},{key:'name',label:'显示名称',placeholder:'例如：苹果 / 贵州茅台'},{key:'targetAbove',label:'价格高于此值时提醒',type:'number',nullable:true,min:0},{key:'targetBelow',label:'价格低于此值时提醒',type:'number',nullable:true,min:0}]
export default function Markets(){
 const {state,setPage,action,notify,demo}=useWorkbench(),[filter,setFilter]=useState('all'),[open,setOpen]=useState(false),[edit,setEdit]=useState<Watch|null>(null),[selected,setSelected]=useState<string|null>(null)
 if(!state)return null
 const watch=state.watchlist.filter(w=>filter==='all'||w.market===filter),active=watch.find(w=>w.id===selected)??watch[0],q=active?state.quotes.find(q=>q.symbol===active.symbol&&q.market===active.market):null
 const series=active?state.quoteHistory?.filter(h=>h.symbol===active.symbol&&h.market===active.market).map(h=>({...h,time:dateTime(h.asOf)}))??[]:[]
 return <div className="page-enter"><SectionTitle eyebrow="MARKET WATCH" title="市场监控" description="关注你的自选，每一份报价都有来源与时间。" action={<Button onClick={()=>{setEdit(null);setOpen(true)}}><Plus size={15}/>添加自选</Button>}/>
 <div className="market-toolbar"><div className="segmented">{[{id:'all',name:'全部市场'},{id:'US',name:'美股'},{id:'CN',name:'A 股'}].map(f=><button key={f.id} className={filter===f.id?'selected':''} onClick={()=>{setFilter(f.id);setSelected(null)}}>{f.name}</button>)}</div><BusyButton onClick={async()=>{const r=await action<{results:{market:string;status:string;message?:string}[]}>('/market/refresh',{});notify(r.results.map(x=>`${x.market==='US'?'美股':'A股'}：${x.status==='ok'?'已刷新':x.message??'未配置'}`).join('；'),r.results.some(x=>x.status==='error')?'error':'success')}}><RefreshCw size={13}/>刷新行情</BusyButton></div>
 <div className="market-layout"><Panel title="自选清单" description={`${watch.length} 个标的 · 点击查看详情`}>{watch.length?<div className="watch-list">{watch.map(w=>{const price=state.quotes.find(q=>q.symbol===w.symbol&&q.market===w.market);return <div key={w.id} className={`watch-row ${active?.id===w.id?'selected':''}`}><button className="watch-select" onClick={()=>setSelected(w.id)}><span className="stock-avatar">{w.symbol.slice(0,2)}</span><span><strong>{w.name||w.symbol}</strong><small>{w.symbol} · {w.market==='US'?'US':'CN'}</small></span><span><strong>{price?money(price.price,price.currency):'—'}</strong><small className={price?.changePercent!=null?(price.changePercent>=0?'positive':'negative'):''}>{price?.changePercent!=null?`${price.changePercent>=0?'+':''}${price.changePercent.toFixed(2)}%`:'等待行情'}</small></span></button><span className="record-actions"><EditButton onClick={()=>{setEdit(w);setOpen(true)}}/><DeleteButton collection="watchlist" id={w.id} name={w.name||w.symbol}/></span></div>})}</div>:<Empty icon={TrendingUp} title="你的观察清单，从这里开始" description="美股填 AAPL 等代码，A 股填 600519.SH、000001.SZ 等代码。" onClick={()=>{setEdit(null);setOpen(true)}} action="添加自选"/>}</Panel>
 <Panel title={active?active.name||active.symbol:'行情详情'} description={active?`${active.symbol} · ${active.market==='US'?'美国市场 · USD':'中国 A 股 · CNY'}`:'选择一个自选标的'} action={q&&<Badge variant="outline" className="badge-blue">{demo?'演示数据':q.latency==='minute'?'分钟源':q.latency==='delayed'?'延迟源':'实时源'}</Badge>}>{q?<><div className="quote-main"><strong>{money(q.price,q.currency)}</strong><span className={q.changePercent!=null?(q.changePercent>=0?'positive':'negative'):'muted'}>{q.changePercent!=null?`${q.changePercent>=0?'+':''}${q.changePercent.toFixed(2)}%`:'未提供涨跌幅'}</span></div><div className="quote-meta"><span><Clock size={12}/>报价于 {dateTime(q.asOf)}</span><span>{q.source}</span></div>{series.length>1?<div className="price-chart"><ResponsiveContainer width="100%" height={215}><AreaChart data={series}><CartesianGrid vertical={false} stroke="var(--chart-grid)" strokeDasharray="4 4"/><XAxis dataKey="time" tickLine={false} axisLine={false} minTickGap={35} tick={{fill:'var(--muted-foreground)',fontSize:9}}/><YAxis domain={['auto','auto']} width={55} tick={{fill:'var(--muted-foreground)',fontSize:10}} tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:10}}/><Area type="linear" dataKey="price" name="价格" stroke="#729bee" fill="#729bee12" connectNulls={false}/></AreaChart></ResponsiveContainer></div>:<div className="history-wait"><Activity size={20}/><p>价格历史将从实际采样逐步积累</p><small>不会根据当前价格生成虚构走势。</small></div>}<div className="quote-detail-grid"><div><span>成交量（来源原单位）</span><strong>{compact(q.volume)}</strong></div><div><span>行情接收时间</span><strong>{dateTime(q.receivedAt)}</strong></div><div><span>市场状态</span><strong>{q.session??'来源未提供'}</strong></div><div><span>监测间隔</span><strong>{state.settings.market.refreshSeconds} 秒</strong></div></div>{Date.now()-Date.parse(q.asOf)>180000&&<div className="info-note"><Info size={14}/><span>这份报价已有一段时间，可能处于休市、延迟或连接失败。请核对报价时间。</span></div>}</>:<Empty icon={Activity} title={active?'尚未取得报价':'等待选择自选'} description="先配置行情 API，随后会按设定间隔集中采样。没有权限时保留清晰的连接状态。" onClick={()=>setPage('settings')} action="配置行情源"/>}</Panel></div>
 <div className="two-columns"><Panel title="美股数据源" description="Alpaca · IEX / SIP / delayed SIP"><div className="detail-row"><span>当前源</span><strong>{state.settings.market.alpacaFeed.toUpperCase()}</strong></div><div className="detail-row"><span>连接配置</span><Badge variant="outline" className={state.settings.market.alpacaKeyConfigured&&state.settings.market.alpacaSecretConfigured?'badge-green':'badge-muted'}>{state.settings.market.alpacaKeyConfigured&&state.settings.market.alpacaSecretConfigured?'已配置':'未配置'}</Badge></div><p className="helper-text">IEX 来自单一交易所，SIP 实时需相应权限。报价源实时不代表网页逐笔实时：本版按间隔采样。</p></Panel><Panel title="A 股数据源" description="Tushare · 实时分钟接口"><div className="detail-row"><span>当前源</span><strong>rt_min · 1MIN</strong></div><div className="detail-row"><span>连接配置</span><Badge variant="outline" className={state.settings.market.tushareKeyConfigured?'badge-green':'badge-muted'}>{state.settings.market.tushareKeyConfigured?'已配置':'未配置'}</Badge></div><p className="helper-text">需要实时分钟接口权限；成交量按接口原单位展示。页面不把分钟数据标为逐笔实时。</p></Panel></div>
 <RecordEditor open={open} onClose={()=>setOpen(false)} collection="watchlist" title={edit?'编辑自选与提醒':'添加自选股票'} fields={fields} record={edit as unknown as Record<string,unknown>}/>
 </div>
}
