import {ArrowUpRight,BookOpen,Check,ChevronRight,Clock,Flame,Plus,Sparkles,Target,TrendingUp,Wallet,Activity} from 'lucide-react'
import {AreaChart,Area,CartesianGrid,Tooltip,XAxis,ResponsiveContainer,BarChart,Bar} from 'recharts'
import {useState} from 'react'
import {useWorkbench} from '../lib/store'
import {buckets,compact,dailyTokens,dateKey,dateTime,money,taskDueState} from '../lib/domain'
import {Panel,Button,Card,CardContent,Badge,Empty,Stat,TaskRow,RecordEditor,taskFields} from '../components/common'
import {QuotaCard} from '../components/quota-card'
import {compareTaskDueAt} from '../lib/task-import'
export default function Overview(){
 const {state,demo,setPage}=useWorkbench(),[addTask,setAddTask]=useState(false)
 if(!state)return <div className="page-loading"><Activity className="spin"/>正在读取你的工作台…</div>
 const today=dateKey(),bucket=buckets(state.codex)[0]?.[1],pending=state.tasks.filter(t=>t.status!=='completed').sort(compareTaskDueAt)
 const plans=state.studyPlans.filter(p=>p.date===today),completed=plans.filter(p=>p.status==='completed').length,minutes=state.studySessions.filter(s=>s.date===today).reduce((a,s)=>a+s.minutes,0)
 const token=dailyTokens(state.codex.dailyUsageBuckets,today),usage=state.codex.dailyUsageBuckets?.slice(-7),study=Array.from({length:7},(_,i)=>{const date=dateKey(new Date(Date.now()-(6-i)*86400000));return {date:date.slice(5),minutes:state.studySessions.filter(s=>s.date===date).reduce((a,s)=>a+s.minutes,0)}})
 return <div className="page-enter"><div className="greeting"><div className="eyebrow">YOUR PERSONAL SPACE</div><h1>你好，{state.settings.profile.name||'学习者'} <span className="greeting-dot">✦</span></h1><p>从这里开始，让学习、工具和信息井然有序。</p></div>
 <div className="welcome-banner"><div><Badge variant="outline" className="banner-badge"><Sparkles size={13}/> 每一天，都向前一点</Badge><h2>把注意力，留给重要的事。</h2><p>{pending.length?`你有 ${pending.length} 项待完成任务，${plans.length} 项今日学习计划。`:'安排今天的学习，掌握工具额度，一眼看清待办。'}<br/>这里是属于你的工作节奏。</p><Button onClick={()=>setPage('study')}>开启今日学习 <ArrowUpRight size={15}/></Button></div><div className="banner-art" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="art-tile large"><BookOpen size={30}/><span>持续积累</span><i/></div><div className="art-tile small"><Check size={20}/></div><div className="art-spark">✦</div><div className="art-dots">···</div></div></div>
 <div className="overview-stats"><QuotaCard window={bucket?.primary} status={state.codex.status} onConnect={()=>setPage('settings')}/><QuotaCard window={bucket?.secondary} kind="secondary" status={state.codex.status} onConnect={()=>setPage('settings')}/><Card className="learning-stat"><CardContent><div className="stat-top"><span>今日学习</span><span className="icon-box amber"><Flame size={18}/></span></div><div className="learning-number">{minutes}<small>分钟</small></div><div className="learning-bar"><span style={{width:`${Math.min(100,minutes/(state.goals[0]?.dailyMinutes||120)*100)}%`}}/></div><div className="learning-foot"><span>{completed} / {plans.length} 项计划已完成</span><button onClick={()=>setPage('study')}>继续学习 <ChevronRight size={14}/></button></div></CardContent></Card></div>
 <div className="overview-middle"><Panel title="AI 使用趋势" description="最近七个来源日的 token 使用记录" action={<button className="text-button" onClick={()=>setPage('quota')}>查看详情 <ArrowUpRight size={14}/></button>}><div className="chart-summary"><strong>{compact(token)}<small>tokens</small></strong><Badge variant="outline" className="badge-muted">{demo?'演示统计':'来源日 '+today}</Badge></div>{usage?.length?<div className="chart-area"><ResponsiveContainer width="100%" height={185}><AreaChart data={usage}><defs><linearGradient id="usageFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3b82f6" stopOpacity={0.2}/><stop offset="100%" stopColor="#3b82f6" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 4" stroke="var(--chart-grid)"/><XAxis dataKey="startDate" tickFormatter={v=>String(v).slice(5)} axisLine={false} tickLine={false} tick={{fill:'var(--muted-foreground)',fontSize:11}} dy={7}/><Tooltip contentStyle={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:10,fontSize:12}} formatter={v=>[Number(v).toLocaleString(),'tokens']}/><Area type="monotone" dataKey="tokens" stroke="#3b82f6" strokeWidth={2.5} fill="url(#usageFill)"/></AreaChart></ResponsiveContainer></div>:<Empty title="等待第一份使用记录" description="连接 Codex 助手后，自动记录用量变化。" onClick={()=>setPage('settings')} action="连接同步助手"/>}</Panel>
 <Panel title="近期截止" description="先完成最接近截止的任务" action={<button className="icon-button" onClick={()=>setAddTask(true)} aria-label="新增任务"><Plus size={17}/></button>}>{pending.length?<><div className="task-list">{pending.slice(0,3).map(t=><TaskRow key={t.id} task={t} compact/>)}</div><button className="panel-link" onClick={()=>setPage('tasks')}>查看全部 {pending.length} 项任务 <ArrowUpRight size={14}/></button></>:<Empty icon={Check} title="暂时没有待完成任务" description="把学习通作业、考试和其他待办记录在这里。" onClick={()=>setAddTask(true)} action="添加任务"/>}</Panel></div>
 <p className="helper-text">{!demo&&state.codex.dailyUsageBuckets?.length?`日统计采样于 ${dateTime(state.codex.dailyUsageObservedAt??state.codex.syncedAt)}；来源日期未换算时区。`:null}</p><div className="overview-bottom"><Panel title="市场速览" description="你的自选，保持关注" action={<button className="text-button" onClick={()=>setPage('markets')}>全部自选 <ArrowUpRight size={14}/></button>}>{state.watchlist.length?<div className="market-mini-list">{state.watchlist.slice(0,4).map(w=>{const q=state.quotes.find(q=>q.symbol===w.symbol&&q.market===w.market);return <button className="market-mini" key={w.id} onClick={()=>setPage('markets')}><span className="stock-avatar">{w.symbol.slice(0,2)}</span><span><strong>{w.name||w.symbol}</strong><small>{w.symbol} · {w.market==='US'?'美股':'A股'}</small></span><span className="mini-quote"><strong>{q?money(q.price,q.currency):'待连接'}</strong><small className={q&&q.changePercent!=null?(q.changePercent>=0?'positive':'negative'):''}>{q?.changePercent!=null?`${q.changePercent>=0?'+':''}${q.changePercent.toFixed(2)}%`:'暂无行情'}</small></span></button>})}</div>:<Empty icon={TrendingUp} title="建立你的市场清单" description="添加美股与 A 股自选，配置行情源后开始监控。" onClick={()=>setPage('markets')} action="添加自选"/>}</Panel>
 <Panel title="学习节奏" description="最近七天的专注时长" action={<span className="icon-box green"><Target size={16}/></span>}><div className="chart-summary"><strong>{study.reduce((n,d)=>n+d.minutes,0)}<small>分钟 / 7 天</small></strong></div><div className="chart-area"><ResponsiveContainer width="100%" height={155}><BarChart data={study}><CartesianGrid vertical={false} stroke="var(--chart-grid)" strokeDasharray="4 4"/><XAxis dataKey="date" tickLine={false} axisLine={false} tick={{fill:'var(--muted-foreground)',fontSize:10}}/><Tooltip formatter={v=>[v,'分钟']} contentStyle={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:10,fontSize:12}}/><Bar dataKey="minutes" fill="#7aa3f5" radius={[5,5,0,0]} maxBarSize={24}/></BarChart></ResponsiveContainer></div></Panel></div>
 <div className="dashboard-foot"><span><span className="status-dot"/> {demo?'此页所有数字均为演示数据':state.sync.connected?'同步助手在线':'工作台已就绪 · 同步助手未连接'}</span><span>慢慢来，比较快。</span></div>
 <RecordEditor open={addTask} onClose={()=>setAddTask(false)} collection="tasks" title="新增学习任务" fields={taskFields} defaults={{source:'manual'}}/>
 </div>
}
