import {useState} from 'react'
import {Activity,ArrowUpRight,Clock,Plus,RefreshCw,Terminal,Wallet,Info} from 'lucide-react'
import {AreaChart,Area,CartesianGrid,Tooltip,XAxis,YAxis,ResponsiveContainer} from 'recharts'
import {useWorkbench} from '../lib/store'
import {buckets,compact,countdown,dateKey,dateTime,money,quotaChartData,dailyQuotaEstimate} from '../lib/domain'
import {Panel,Button,Badge,Empty,SectionTitle,RecordEditor,DeleteButton,EditButton,BusyButton,Progress,type Field} from '../components/common'
import {QuotaCard} from '../components/quota-card'
import type {Account} from '../lib/types'
const accountFields:Field[]=[{key:'name',label:'账户名称',required:true,placeholder:'例如：Claude Pro'},{key:'provider',label:'平台',placeholder:'OpenAI / DeepSeek / 自定义'},{key:'type',label:'账户类型',type:'select',default:'api',options:[{value:'api',label:'API 余额 / 预算'},{value:'subscription',label:'订阅额度'}]},{key:'currency',label:'币种 / 单位',type:'select',default:'CNY',options:[{value:'CNY',label:'人民币 CNY'},{value:'USD',label:'美元 USD'},{value:'percent',label:'百分比 %'}]},{key:'balance',label:'剩余余额 / 额度',type:'number',nullable:true,min:0},{key:'total',label:'总预算 / 总额度（可选）',type:'number',nullable:true,min:0},{key:'resetsAt',label:'下次刷新（可选）',type:'datetime-local',nullable:true},{key:'threshold',label:'低余额提醒阈值（可选）',type:'number',nullable:true,min:0},{key:'note',label:'备注',type:'textarea'}]
export default function Quota(){
 const {state,demo,setPage,action,notify}=useWorkbench(),[open,setOpen]=useState(false),[edit,setEdit]=useState<Account|null>(null),[filter,setFilter]=useState('all')
 if(!state)return null
 const allBuckets=buckets(state.codex),history=quotaChartData(state.codex.history),estimate=dailyQuotaEstimate(state.codex.history),accounts=state.accounts.filter(a=>filter==='all'||a.type===filter)
 return <div className="page-enter"><SectionTitle eyebrow="AI RESOURCES" title="AI 额度与余额" description="掌握每个平台的使用空间，安排好下一次专注。" action={<Button onClick={()=>{setEdit(null);setOpen(true)}}><Plus size={15}/>添加账户</Button>}/>
 <div className="section-line"><h2><Terminal size={17}/>Codex 订阅额度</h2><span className="muted">{demo?'演示数据':`最后成功同步：${dateTime(state.codex.syncedAt)}`}</span></div>{allBuckets.length?allBuckets.map(([id,b])=><div key={id}><div className="bucket-label">{b.limitName||id}</div><div className="quota-grid"><QuotaCard window={b.primary} status={state.codex.status}/><QuotaCard window={b.secondary} kind="secondary" status={state.codex.status}/><Panel title="账户信息" description="额度、token 与付费余额分别记录"><div className="detail-row"><span>额度来源</span><strong>{demo?'演示数据':'Codex App Server'}</strong></div><div className="detail-row"><span>同步状态</span><Badge variant="outline" className={state.codex.status==='ok'?'badge-green':'badge-amber'}>{state.codex.status==='ok'?'已同步':state.codex.status==='stale'?'数据已过期':state.codex.status==='error'?'同步失败':'等待连接'}</Badge></div><div className="detail-row"><span>剩余 credits</span><strong>{b.credits?.unlimited?'不限量':b.credits?.balance??'未提供'}</strong></div>{state.codex.error&&<p className="helper-text">最近尝试：{state.codex.error}。保留上次成功采样结果。</p>}</Panel></div></div>):<div className="quota-grid"><QuotaCard window={null} status="unconfigured" onConnect={()=>setPage('settings')}/><QuotaCard window={null} kind="secondary" status="unconfigured" onConnect={()=>setPage('settings')}/><Panel title="连接本机同步助手"><Empty icon={Terminal} title="让额度自动更新" description="在设置中生成同步令牌，再在已登录 Codex 的电脑上启动助手。" onClick={()=>setPage('settings')} action="查看接入方式"/></Panel></div>}
 <Panel title="今日监测期间额度变化" description="北京时间当天 · 相邻成功采样的已用量变化估算" action={<Badge variant="outline" className="badge-muted">{estimate.sampleCount} 次有效采样</Badge>}><div className="detail-row"><span>短窗口已用量增长</span><strong>{estimate.primary==null?'—':`${Number(estimate.primary.toFixed(2))} 个百分点`}</strong></div><div className="detail-row"><span>长窗口已用量增长</span><strong>{estimate.secondary==null?'—':`${Number(estimate.secondary.toFixed(2))} 个百分点`}</strong></div><p className="helper-text">默认额度桶 · 监测区间 {dateTime(estimate.from)} 至 {dateTime(estimate.to)}。跳过 {estimate.skippedPairs} 段重置、缺失、回落或超过 5 分钟的间隔。这是实际可比较区间的变化估算，受取整与漏采样影响，不代表完整日消耗，不换算为 token 或费用。</p></Panel>
<div className="two-columns quota-charts"><Panel title="额度历史" description="剩余百分比 · 从首次监测开始，不累计为日总额" action={<Badge variant="outline" className="badge-muted">最近 {history.length} 次采样</Badge>}>{history.length?<ResponsiveContainer width="100%" height={200}><AreaChart data={history}><CartesianGrid vertical={false} strokeDasharray="4 4" stroke="var(--chart-grid)"/><XAxis dataKey="time" axisLine={false} tickLine={false} minTickGap={25} tick={{fill:'var(--muted-foreground)',fontSize:10}}/><YAxis domain={[0,100]} tick={{fill:'var(--muted-foreground)',fontSize:10}} tickLine={false} axisLine={false} width={30}/><Tooltip contentStyle={{background:'var(--card)',border:'1px solid var(--border)',borderRadius:9}}/><Area connectNulls={false} type="linear" dataKey="remaining" name="短窗口剩余 %" stroke="#729bee" fill="#729bee15"/><Area connectNulls={false} type="linear" dataKey="weekly" name="长窗口剩余 %" stroke="#ab96dd" fill="#ab96dd0a"/></AreaChart></ResponsiveContainer>:<Empty title="还没有历史采样" description="连接后自动积累，离线期间不补造使用数据。"/>}</Panel><Panel title="每日用量" description="源接口提供的日期与 token 数，不等同于额度百分比">{state.codex.dailyUsageBuckets?.length?<div className="daily-table"><div className="table-label"><span>来源日期</span><span>tokens</span></div>{state.codex.dailyUsageBuckets.slice(-7).reverse().map(d=><div className="daily-row" key={d.startDate}><span>{d.startDate}</span><strong>{compact(d.tokens)}</strong></div>)}</div>:<Empty icon={Activity} title="日统计暂未提供" description="部分账号或版本不返回每日用量。不会用周额度反推今日消耗。"/>}<p className="helper-text">最近日统计采样：{dateTime(state.codex.dailyUsageObservedAt??state.codex.syncedAt)}。来源的统计时区未确认时，保留原始日期；不能直接换算为人民币或美元费用。</p></Panel></div>
 <div className="section-line account-section"><h2><Wallet size={17}/>其他平台账户</h2><BusyButton onClick={async()=>{const r=await action<{results:{provider:string;status:string;message?:string}[]}>('/providers/balances/refresh',{});notify(r.results.map(x=>`${x.provider}: ${x.status==='ok'?'已同步':x.message??'未配置'}`).join('；'),r.results.some(x=>x.status==='error')?'error':'success')}}><RefreshCw size={13}/>同步 API 余额</BusyButton></div>
 <div className="currency-summary"><span>人民币余额 <strong>{money(state.accounts.filter(a=>a.currency==='CNY'&&a.balance!=null).reduce((n,a)=>n+(a.balance??0),0),'CNY')}</strong></span><span>美元余额 <strong>{money(state.accounts.filter(a=>a.currency==='USD'&&a.balance!=null).reduce((n,a)=>n+(a.balance??0),0),'USD')}</strong></span><small>按币种分别统计 · 手动预算与官方余额请查看来源</small></div>
 <Panel title="账户清单" action={<div className="segmented">{[{value:'all',label:'全部'},{value:'api',label:'API'},{value:'subscription',label:'订阅'}].map(f=><button className={filter===f.value?'selected':''} key={f.value} onClick={()=>setFilter(f.value)}>{f.label}</button>)}</div>}>{accounts.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>账户</th><th>类型 / 来源</th><th>剩余</th><th>下次刷新</th><th>备注</th><th/></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.provider||'自定义平台'}</small></td><td><Badge variant="outline" className="badge-muted">{a.type==='api'?'API':'订阅'}</Badge><small>{a.source==='api'?'官方接口':'手动记录'}</small></td><td><strong className="number">{money(a.balance,a.currency)}</strong>{a.total!=null&&a.total>0&&a.balance!=null&&<div className="balance-progress"><Progress value={Math.min(100,a.balance/a.total*100)}/></div>}</td><td className="muted">{a.resetsAt?dateTime(a.resetsAt):'—'}</td><td><p className="table-note">{a.note||'—'}</p></td><td><span className="record-actions">{a.source==='manual'&&<EditButton onClick={()=>{setEdit(a);setOpen(true)}}/>}<DeleteButton collection="accounts" id={a.id} name={a.name}/></span></td></tr>)}</tbody></table></div>:<Empty icon={Wallet} title="添加你的第一个 AI 账户" description="支持订阅额度、API 余额和手动预算记录。" onClick={()=>{setEdit(null);setOpen(true)}} action="添加账户"/>}</Panel>
 <div className="info-note"><Info size={15}/><span>DeepSeek 可查询官方余额；OpenAI Costs API 返回费用，需要组织管理员权限。其他服务先手动记录，在确认接口后接入。</span><button onClick={()=>setPage('settings')}>配置 API <ArrowUpRight size={13}/></button></div>
 <RecordEditor open={open} onClose={()=>setOpen(false)} collection="accounts" title={edit?'编辑账户':'添加 AI 账户'} fields={accountFields} record={edit as unknown as Record<string,unknown>} defaults={{source:'manual'}}/>
 </div>
}
