import {useState,useEffect,type ReactNode} from 'react'
import {Save,KeyRound,Terminal,Copy,Download,Upload,ShieldCheck,RefreshCw,Info} from 'lucide-react'
import {useWorkbench} from '../lib/store'
import {api} from '../lib/api'
import {dateTime} from '../lib/domain'
import {Panel,Button,Badge,SectionTitle,Modal,BusyButton} from '../components/common'
import type {Settings as SettingsType} from '../lib/types'
function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Secret({label,configured,value,onChange,name,clear,onClear}:{label:string;configured:boolean;value:string;onChange:(v:string)=>void;name:string;clear:string[];onClear:(v:string[])=>void}){return <div className="secret-field"><Field label={label} hint={configured?'已保存 · 留空保留现有密钥':'尚未配置'}><input type="password" autoComplete="new-password" value={value} onChange={e=>onChange(e.target.value)} placeholder={configured?'已加密保存，不回显密钥':'粘贴 API 密钥'}/></Field>{configured&&<label className="check-field"><input type="checkbox" checked={clear.includes(name)} onChange={e=>onClear(e.target.checked?[...clear,name]:clear.filter(n=>n!==name))}/>清除此密钥</label>}</div>}
export default function Settings(){
 const {state,demo,action,notify}=useWorkbench(),[draft,setDraft]=useState<SettingsType|null>(null),[secrets,setSecrets]=useState<Record<string,string>>({}),[clear,setClear]=useState<string[]>([]),[saving,setSaving]=useState(false),[token,setToken]=useState(''),[tokenOpen,setTokenOpen]=useState(false),[restoreOpen,setRestoreOpen]=useState(false),[backup,setBackup]=useState<Record<string,unknown>|null>(null),[restoreError,setRestoreError]=useState(''),[passwordOpen,setPasswordOpen]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirm,setConfirm]=useState(''),[passwordError,setPasswordError]=useState('')
 useEffect(()=>{if(state&&!draft)setDraft(structuredClone(state.settings))},[state,draft])
 if(!state||!draft)return null
 const setAi=(key:string,v:unknown)=>setDraft({...draft,ai:{...draft.ai,[key]:v}}),setSecret=(name:string,v:string)=>setSecrets({...secrets,[name]:v})
 const secret=(label:string,name:string,configured:boolean)=><Secret label={label} name={name} configured={configured} value={secrets[name]??''} onChange={v=>setSecret(name,v)} clear={clear} onClear={setClear}/>
 const save=async()=>{setSaving(true);try{const a=draft.ai;const result=await action<SettingsType>('/settings',{profile:draft.profile,ai:{provider:a.provider,baseUrl:a.baseUrl,model:a.model,dailyRequestLimit:a.dailyRequestLimit,dailyBudget:a.dailyBudget??null,maxTokens:a.maxTokens,inputPrice:a.inputPrice,outputPrice:a.outputPrice,currency:a.currency,...(secrets['ai.apiKey']?{apiKey:secrets['ai.apiKey']}:{})},deepseek:{...(secrets['deepseek.apiKey']?{apiKey:secrets['deepseek.apiKey']}:{})},openai:{...(secrets['openai.apiKey']?{apiKey:secrets['openai.apiKey']}:{})},notifications:draft.notifications,clearSecrets:clear},'PUT');setDraft(result);setSecrets({});setClear([]);notify('设置已保存，密钥不会在浏览器中回显')}catch(e){notify((e as Error).message,'error')}finally{setSaving(false)}}
 return <div className="page-enter settings-page"><SectionTitle eyebrow="YOUR SPACE, YOUR RULES" title="工作台设置" description="配置你的连接、偏好与提醒，后续都可以在这里修改。" action={<Button disabled={saving||demo} onClick={()=>void save()}><Save size={15}/>{saving?'正在保存…':'保存设置'}</Button>}/>
 <form onSubmit={e=>{e.preventDefault();void save()}}><div className="settings-grid"><Panel title="个人偏好" description="全站日期与每日用量分组使用北京时间"><div className="form-grid"><Field label="显示名称"><input value={draft.profile.name} maxLength={100} onChange={e=>setDraft({...draft,profile:{...draft.profile,name:e.target.value}})} placeholder="你的昵称"/></Field><Field label="时区"><select value="Asia/Shanghai" disabled><option>Asia/Shanghai</option></select></Field></div></Panel>
 <Panel title="提醒规则" description="页面刷新时生成提醒，点击右上角铃铛查看"><div className="form-grid"><Field label="额度剩余低于（%）"><input type="number" min="0" max="100" value={draft.notifications.quotaBelow} onChange={e=>setDraft({...draft,notifications:{...draft.notifications,quotaBelow:Number(e.target.value)}})}/></Field><Field label="默认低余额阈值"><input type="number" min="0" value={draft.notifications.balanceBelow} onChange={e=>setDraft({...draft,notifications:{...draft.notifications,balanceBelow:Number(e.target.value)}})}/></Field><Field label="任务提前提醒（小时）"><input type="number" min="0" max="720" value={draft.notifications.taskHours} onChange={e=>setDraft({...draft,notifications:{...draft.notifications,taskHours:Number(e.target.value)}})}/></Field></div></Panel>
 <Panel className="settings-wide" title="AI 学习与需求分析接口" description="支持 DeepSeek、OpenAI 和兼容 Chat Completions 的 HTTPS 接口" action={<Badge className={state.settings.ai.keyConfigured?'badge-green':'badge-muted'} variant="outline">{state.settings.ai.keyConfigured?'密钥已配置':'尚未接入'}</Badge>}><div className="form-grid three"><Field label="服务商"><select value={draft.ai.provider} onChange={e=>{const v=e.target.value;setDraft({...draft,ai:{...draft.ai,provider:v,baseUrl:v==='deepseek'?'https://api.deepseek.com':v==='openai'?'https://api.openai.com/v1':draft.ai.baseUrl,model:v==='deepseek'?'deepseek-chat':v==='openai'?'gpt-4.1-mini':draft.ai.model}})}}><option value="deepseek">DeepSeek</option><option value="openai">OpenAI</option><option value="custom">其他兼容接口</option></select></Field><Field label="模型名称"><input value={draft.ai.model} required onChange={e=>setAi('model',e.target.value)}/></Field><Field label="接口 Base URL" hint="例如 https://api.example.com/v1"><input type="url" value={draft.ai.baseUrl} required onChange={e=>setAi('baseUrl',e.target.value)}/></Field>{secret('AI 独立密钥','ai.apiKey',state.settings.ai.keyConfigured)}<Field label="每日请求上限"><input type="number" min="1" max="1000" value={draft.ai.dailyRequestLimit} onChange={e=>setAi('dailyRequestLimit',Number(e.target.value))}/></Field><Field label="单次最大输出 tokens"><input type="number" min="1" max="16384" value={draft.ai.maxTokens} onChange={e=>setAi('maxTokens',Number(e.target.value))}/></Field><Field label="输入单价 / 百万 tokens"><input type="number" min="0" max="10000" step="any" value={draft.ai.inputPrice} onChange={e=>setAi('inputPrice',Number(e.target.value))}/></Field><Field label="输出单价 / 百万 tokens"><input type="number" min="0" max="10000" step="any" value={draft.ai.outputPrice} onChange={e=>setAi('outputPrice',Number(e.target.value))}/></Field><Field label="估算费用币种"><select value={draft.ai.currency} onChange={e=>setAi('currency',e.target.value)}><option value="CNY">人民币 CNY</option><option value="USD">美元 USD</option></select></Field><Field label="每日估算费用阈值（选填）" hint="留空关闭。需先设置单价。"><input type="number" min="0.01" step="any" value={draft.ai.dailyBudget??''} onChange={e=>setAi('dailyBudget',e.target.value===''?null:Number(e.target.value))}/></Field></div><p className="helper-text">独立密钥优先；未配置时可使用相应平台的余额查询密钥。学习与需求分析共用此配置和每日限额，请求会按填写的地址发送，切换地址前请核对密钥归属。费用由你填写的单价估算；达到阈值后阻止下一次请求，单次生成及未返回用量的请求仍可能超出。</p></Panel>
 <Panel title="API 余额与费用" description="不同币种分别展示，官方费用不当作剩余额度"><div className="form-grid single">{secret('DeepSeek API 密钥','deepseek.apiKey',state.settings.deepseek.keyConfigured)}{secret('OpenAI 组织管理员密钥','openai.apiKey',state.settings.openai.keyConfigured)}</div><p className="helper-text">DeepSeek 查询余额。OpenAI 查询当月组织费用，需 Costs API 权限；费用查询结果不会伪造为账户余额。</p></Panel>
 </div><div className="settings-save"><span>密钥加密保存在服务器，页面只显示配置状态。</span><Button type="submit" disabled={saving||demo}><Save size={15}/>保存设置</Button></div></form>
 <div className="two-columns settings-tools"><Panel title={<span className="inline-title"><Terminal size={17}/>本机同步助手</span>} description="读取已登录 Codex 的额度，向工作台上传精简快照"><div className="detail-row"><span>同步令牌</span><Badge variant="outline" className={state.settings.agent.tokenConfigured?'badge-green':'badge-muted'}>{state.settings.agent.tokenConfigured?'已生成':'未生成'}</Badge></div><div className="detail-row"><span>最近连接</span><strong>{dateTime(state.sync.lastSeen)}</strong></div><p className="body-copy">在安装 Codex 的电脑运行 <code>node agent/index.mjs</code>，配置 WORKBENCH_URL 与 WORKBENCH_AGENT_TOKEN。默认每 60 秒采样，失败时自动退避重试。</p><Button variant="outline" disabled={demo} onClick={()=>{setToken('');setTokenOpen(true)}}><KeyRound size={14}/>{state.settings.agent.tokenConfigured?'轮换同步令牌':'生成同步令牌'}</Button><p className="helper-text">详细步骤见源码 docs/SYNC.md。学习通自动读取待真实会话验证，本版支持任务导入。</p></Panel>
 <Panel title={<span className="inline-title"><ShieldCheck size={17}/>数据与账户</span>} description="记录归你所有，可导出备份后迁移服务器"><div className="data-actions"><BusyButton onClick={async()=>{if(demo)throw new Error('请退出演示后导出真实数据');const data=await api('/backup');if(new TextEncoder().encode(JSON.stringify({backup:data,mode:'merge'})).length>64_000_000)throw new Error('记录超过恢复容量，请备份完整 data 目录');const file=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});if(file.size>64_000_000)throw new Error('记录备份超过 64 MB，请停止服务后备份完整 data 目录');const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=`workbench-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('备份已导出，不包含密码、API 密钥或同步令牌')}}><Download size={14}/>导出记录</BusyButton><Button variant="outline" disabled={demo} onClick={()=>{setRestoreOpen(true);setBackup(null);setRestoreError('')}}><Upload size={14}/>导入备份</Button><Button variant="outline" disabled={demo} onClick={()=>{setPasswordOpen(true);setCurrentPassword('');setNewPassword('');setConfirm('');setPasswordError('')}}><KeyRound size={14}/>修改密码</Button></div><p className="helper-text">JSON 备份包含需求、咨询、任务、目标、学习记录和聊天；密钥与密码不随文件导出。完整迁移需保留服务器 data 目录及加密 key 文件。</p></Panel></div>
 <Modal open={tokenOpen} onClose={()=>{setTokenOpen(false);setToken('')}} title={token?'保存你的同步令牌':'生成同步令牌'} description={token?'令牌仅在这里显示一次，关闭后不能再查看。复制到本机助手环境配置。':'生成后旧令牌立即失效，需要同步更新本机助手的配置。'}>{token?<><code className="token-value">{token}</code><div className="dialog-footer"><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(token);notify('已复制同步令牌')}catch{notify('浏览器未允许复制，请手动选择并复制','error')}}}><Copy size={14}/>复制令牌</Button><Button onClick={()=>{setToken('');setTokenOpen(false)}}>已保存，关闭</Button></div></>:<div className="dialog-footer"><Button variant="outline" onClick={()=>setTokenOpen(false)}>取消</Button><BusyButton variant="default" onClick={async()=>{const r=await action<{token:string}>('/agent/token',{});setToken(r.token)}}><RefreshCw size={14}/>生成新令牌</BusyButton></div>}</Modal>
 <Modal open={restoreOpen} onClose={()=>setRestoreOpen(false)} title="导入工作台备份" description="合并较新的记录，保留已有其他记录。导入的额度快照不会替换实时数据。"><Field label="选择 JSON 备份（最大 64 MB）"><input type="file" accept=".json,application/json" onChange={async e=>{setRestoreError('');setBackup(null);try{const f=e.target.files?.[0];if(!f)return;if(f.size>64_000_000)throw new Error('文件超过 64 MB，请使用完整 data 目录备份迁移');const b=JSON.parse(await f.text());if(b.version!==1||!b.records||typeof b.records!=='object')throw new Error('请选择版本 1 的工作台备份');if(new TextEncoder().encode(JSON.stringify({backup:b,mode:'merge'})).length>64_000_000)throw new Error('导入请求超过 64 MB，请备份完整 data 目录');setBackup(b)}catch(e){setRestoreError((e as Error).message)}}}/></Field>{backup&&<div className="backup-counts">{Object.entries(backup.records as Record<string,unknown>).map(([key,list])=><span key={key}>{key} <strong>{Array.isArray(list)?list.length:'格式无效'}</strong></span>)}</div>}{restoreError&&<div className="form-error">{restoreError}</div>}<div className="dialog-footer"><Button variant="outline" onClick={()=>setRestoreOpen(false)}>取消</Button><BusyButton variant="default" onClick={async()=>{if(!backup)throw new Error('请先选择备份文件');const r=await action<{counts:Record<string,number>}>('/backup/restore',{backup,mode:'merge'});notify(`已合并 ${Object.values(r.counts).reduce((a,b)=>a+b,0)} 条记录`);setRestoreOpen(false)}}><Upload size={14}/>确认合并</BusyButton></div></Modal>
 <Modal open={passwordOpen} onClose={()=>setPasswordOpen(false)} title="修改个人密码" description="修改后其他设备会退出登录，当前设备保持登录。"><form onSubmit={async e=>{e.preventDefault();setPasswordError('');if(newPassword!==confirm){setPasswordError('两次新密码不一致');return}try{await action('/auth/password',{currentPassword,newPassword});setPasswordOpen(false);setCurrentPassword('');setNewPassword('');setConfirm('');notify('密码已修改')}catch(e){setPasswordError((e as Error).message)}}}><div className="form-grid single"><Field label="当前密码"><input type="password" autoComplete="current-password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></Field><Field label="新密码（至少 12 个字符）"><input type="password" autoComplete="new-password" required minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Field><Field label="确认新密码"><input type="password" autoComplete="new-password" required minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)}/></Field></div>{passwordError&&<div className="form-error">{passwordError}</div>}<div className="dialog-footer"><Button type="button" variant="outline" onClick={()=>setPasswordOpen(false)}>取消</Button><Button type="submit">保存新密码</Button></div></form></Modal>
 <div className="info-note"><Info size={14}/><span>以后接入域名时，将本站部署到服务器，通过 HTTPS 反向代理访问；本机助手继续从电脑主动上传。</span></div>
 </div>
}
