import {useState,useEffect,useRef} from 'react'
import {Plus,Target,GraduationCap,BookOpen,Sparkles,Send,StopCircle,Play,Pause,Check,ArrowUpRight,Clock,CalendarDays,NotebookPen,Save,ChevronRight} from 'lucide-react'
import {useWorkbench} from '../lib/store'
import {dateKey,dateTime,compact,money} from '../lib/domain'
import {SSEParser} from '../lib/sse'
import {Panel,Button,Badge,SectionTitle,Empty,RecordEditor,EditButton,DeleteButton,Progress,planFields,type Field} from '../components/common'
import type {Goal,Plan,Mistake} from '../lib/types'
const goalFields:Field[]=[{key:'exam',label:'目标类型',type:'select',default:'postgraduate',options:[{value:'postgraduate',label:'研究生入学考试'},{value:'cet4',label:'英语四级'},{value:'cet6',label:'英语六级'}]},{key:'title',label:'目标名称',required:true,placeholder:'目标院校、专业或分数'},{key:'targetDate',label:'目标日期',type:'date',nullable:true},{key:'subjects',label:'科目（用顿号或逗号分隔）',placeholder:'数学、英语、专业课'},{key:'dailyMinutes',label:'每日学习目标（分钟）',type:'number',default:120,min:1,max:1440,required:true}]
const mistakeFields:Field[]=[{key:'subject',label:'科目',required:true},{key:'nextReview',label:'下次复习时间',type:'datetime-local',nullable:true},{key:'question',label:'题目 / 易错知识点',type:'textarea',required:true},{key:'answer',label:'答案与正确思路',type:'textarea'},{key:'notes',label:'错误原因与复习备注',type:'textarea'}]
const modes=[{id:'tutor',name:'知识辅导',icon:GraduationCap},{id:'plan',name:'学习计划',icon:CalendarDays},{id:'essay',name:'作文批改',icon:NotebookPen},{id:'reading',name:'阅读训练',icon:BookOpen},{id:'translation',name:'翻译练习',icon:Sparkles}]
export default function Study(){
 const {state,demo,setPage,save,notify,refresh,timer,setTimer}=useWorkbench(),[tab,setTab]=useState('plan'),[goalOpen,setGoalOpen]=useState(false),[goalEdit,setGoalEdit]=useState<Goal|null>(null),[planOpen,setPlanOpen]=useState(false),[planEdit,setPlanEdit]=useState<Plan|null>(null),[mistakeOpen,setMistakeOpen]=useState(false),[mistakeEdit,setMistakeEdit]=useState<Mistake|null>(null),[mode,setMode]=useState('tutor'),[selectedGoal,setSelectedGoal]=useState(''),[message,setMessage]=useState(''),[reply,setReply]=useState(''),[sending,setSending]=useState(false),[streamError,setStreamError]=useState(''),[streamUsage,setStreamUsage]=useState<Record<string,unknown>|null>(null),[saveContent,setSaveContent]=useState(''),[now,setNow]=useState(Date.now()),[savingTimer,setSavingTimer]=useState(false)
 const abort=useRef<AbortController|null>(null),chatEnd=useRef<HTMLDivElement>(null)
 useEffect(()=>{const tick=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(tick);abort.current?.abort()}},[])
 useEffect(()=>{chatEnd.current?.scrollIntoView({block:'nearest',behavior:'smooth'})},[reply,sending])
 if(!state)return null
 const today=dateKey(),plans=state.studyPlans.filter(p=>p.date===today),todayMinutes=state.studySessions.filter(s=>s.date===today).reduce((n,s)=>n+s.minutes,0),seconds=timer.elapsed+(timer.startedAt?Math.max(0,Math.floor((now-timer.startedAt)/1000)):0),donePlans=plans.filter(p=>p.status==='completed').length
 const send=async()=>{if(!message.trim()||sending)return;if(demo){notify('演示模式不会调用 API，请退出演示并配置学习 API。','error');return}setSending(true);setReply('');setStreamError('');setStreamUsage(null);const controller=new AbortController();abort.current=controller;let reader:ReadableStreamDefaultReader<Uint8Array>|undefined;let done=false
 try{const response=await fetch('/api/study/chat',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:message.trim(),mode,...(selectedGoal?{goalId:selectedGoal}:{})}),signal:controller.signal});if(!response.ok){const r=await response.json();throw new Error(r.error??'学习 API 连接失败')}if(!response.body)throw new Error('未收到 AI 回复');setMessage('');reader=response.body.getReader();const parser=new SSEParser(),decoder=new TextDecoder();while(true){const chunk=await reader.read();if(chunk.done)break;for(const event of parser.push(decoder.decode(chunk.value,{stream:true}))){if(event.type==='delta')setReply(r=>r+(event.text??''));if(event.type==='error')throw new Error(event.error??'AI 回复中断');if(event.type==='done'){done=true;setStreamUsage(event.usage??null)}}}if(!done)throw new Error('AI 回复中断，尚未保存完整回答');await refresh()}catch(e){setStreamError((e as Error).name==='AbortError'?'已停止生成，不完整回答未保存':(e as Error).message);await refresh()}finally{await reader?.cancel().catch(()=>{});setSending(false);abort.current=null}}
 return <div className="page-enter"><SectionTitle eyebrow="学习与成长" title="学习中心" description="把目标拆成今天能完成的一小步，持续积累。" action={<Button onClick={()=>{setGoalEdit(null);setGoalOpen(true)}}><Plus size={15}/>设置学习目标</Button>}/>
 <div className="goals-grid">{state.goals.length?state.goals.map(g=>{const days=g.targetDate?Math.max(0,Math.ceil((Date.parse(g.targetDate)-Date.now())/86400000)):null;return <Panel key={g.id} title={<span className="inline-title">{g.exam==='postgraduate'?<GraduationCap size={17}/>:<BookOpen size={17}/>} {g.title}</span>} action={<span className="record-actions"><EditButton onClick={()=>{setGoalEdit(g);setGoalOpen(true)}}/><DeleteButton collection="goals" id={g.id} name={g.title}/></span>}><div className="goal-days"><strong>{days??'—'}</strong><span>{days===null?'设置目标日期后显示倒计时':'天，距离目标日'}</span></div><div className="goal-tags">{g.subjects.map(s=><Badge variant="outline" className="badge-muted" key={s}>{s}</Badge>)}</div><div className="goal-footer"><span>每日目标 {g.dailyMinutes} 分钟</span><button onClick={()=>{setSelectedGoal(g.id);setMode('plan');setTab('ai');setMessage(`请根据我的学习目标，安排一个可执行的七天学习计划。`)}}>规划学习 <ArrowUpRight size={13}/></button></div></Panel>}):<Panel title="为自己设一个方向"><Empty icon={Target} title="你的目标，决定你的计划" description="填写考研目标或四六级目标，在科目与日期明确后安排每日学习。" onClick={()=>{setGoalEdit(null);setGoalOpen(true)}} action="设置学习目标"/></Panel>}</div>
 <div className="study-tabs segmented">{[{id:'plan',name:'计划与专注'},{id:'ai',name:'AI 学习助手'},{id:'mistakes',name:'错题与复习'}].map(t=><button key={t.id} className={tab===t.id?'selected':''} onClick={()=>setTab(t.id)}>{t.name}</button>)}</div>
 {tab==='plan'&&<><div className="study-layout"><Panel title="今日学习计划" description={`${donePlans} / ${plans.length} 项已完成`} action={<button className="text-button" onClick={()=>{setPlanEdit(null);setSaveContent('');setPlanOpen(true)}}><Plus size={14}/>添加计划</button>}>{plans.length?<div className="plan-list">{plans.map(p=><div className="plan-row" key={p.id}><button className={`task-check ${p.status==='completed'?'checked':''}`} aria-label={`${p.status==='completed'?'恢复':'完成'}${p.title}`} disabled={demo} onClick={async()=>{try{await save('studyPlans',{status:p.status==='completed'?'pending':'completed'},p.id)}catch(e){notify((e as Error).message,'error')}}}>{p.status==='completed'&&<Check size={13}/>}</button><div><strong className={p.status==='completed'?'strike':''}>{p.title}</strong><small>{p.subject} <span className="dot">·</span> {p.minutes} 分钟</small>{p.content&&<details><summary>查看步骤</summary><p>{p.content}</p></details>}</div><span className="record-actions"><EditButton onClick={()=>{setPlanEdit(p);setSaveContent('');setPlanOpen(true)}}/><DeleteButton collection="studyPlans" id={p.id} name={p.title}/></span></div>)}</div>:<Empty icon={CalendarDays} title="今天，先完成一件事" description="添加一项学习计划，或让 AI 帮你拆解目标。" onClick={()=>{setPlanEdit(null);setSaveContent('');setPlanOpen(true)}} action="添加今日计划"/>}<div className="plan-progress"><Progress value={plans.length?donePlans/plans.length*100:0}/><small>完成计划与专注时长分别记录。</small></div></Panel>
 <Panel title="专注计时" description="切换页面仍保留计时；结束后保存记录"><div className="focus-timer"><span className="timer-label"><Clock size={12}/>给重要的事一点时间</span><strong>{[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(n=>String(n).padStart(2,'0')).join(':')}</strong><input aria-label="专注科目" value={timer.subject} disabled={timer.startedAt!==null} onChange={e=>setTimer({...timer,subject:e.target.value})} placeholder="输入学习科目"/><div className="timer-actions"><Button variant="outline" onClick={()=>{if(timer.startedAt)setTimer({...timer,startedAt:null,elapsed:seconds});else setTimer({...timer,startedAt:Date.now()})}}>{timer.startedAt?<><Pause size={14}/>暂停</>:<><Play size={14}/>{seconds?'继续':'开始专注'}</>}</Button><Button disabled={demo||savingTimer||seconds<1||!timer.subject.trim()} onClick={async()=>{setSavingTimer(true);try{const minutes=Math.min(1440,Math.max(1,Math.ceil(seconds/60)));await save('studySessions',{subject:timer.subject,minutes,date:today});setTimer({...timer,startedAt:null,elapsed:0});notify(`已记录 ${minutes} 分钟专注`)}catch(e){notify((e as Error).message,'error')}finally{setSavingTimer(false)}}}><Check size={14}/>结束并保存</Button></div><small>今日已记录 {todayMinutes} 分钟 · 未满一分钟按一分钟记录</small></div></Panel></div>
 <Panel title="学习记录" description="最近的积累，都是向前的证据" action={<button className="text-button" onClick={()=>{const total=state.studySessions.reduce((n,s)=>n+s.minutes,0);notify(`累计记录 ${state.studySessions.length} 次学习，共 ${total} 分钟`)}}>累计统计 <ArrowUpRight size={13}/></button>}>{state.studySessions.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>日期</th><th>科目</th><th>专注时长</th><th/></tr></thead><tbody>{state.studySessions.slice(-10).reverse().map(s=><tr key={s.id}><td>{s.date}</td><td>{s.subject}</td><td>{s.minutes} 分钟</td><td><DeleteButton collection="studySessions" id={s.id} name={`${s.date} ${s.subject}学习记录`}/></td></tr>)}</tbody></table></div>:<Empty icon={Clock} title="还没有学习记录" description="开始专注计时，结束后保存第一份学习记录。"/>}</Panel></>}
 {tab==='ai'&&<Panel title={<span className="inline-title"><Sparkles size={17}/>AI 学习助手</span>} description="辅导、计划、英语阅读、翻译与作文反馈" action={<Badge variant="outline" className={state.settings.ai.keyConfigured?'badge-green':'badge-muted'}>{state.settings.ai.keyConfigured?state.settings.ai.model:'未配置 API'}</Badge>}><div className="ai-modes">{modes.map(m=><button key={m.id} className={mode===m.id?'selected':''} onClick={()=>setMode(m.id)}><m.icon size={14}/>{m.name}</button>)}</div><div className="ai-goal"><label>当前学习目标</label><select value={selectedGoal} onChange={e=>setSelectedGoal(e.target.value)}><option value="">通用学习辅导</option>{state.goals.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></div><div className="chat-window">{!state.chatMessages.length&&!sending&&!reply?<div className="chat-intro"><span className="chat-spark"><Sparkles size={24}/></span><h3>今天，你想掌握什么？</h3><p>从一个具体问题开始。先说说你已经理解的部分，<br/>我会帮你梳理下一步。</p><div className="prompt-examples">{['帮我制定七天学习计划','给我一篇六级阅读练习并讲解','辅导我分析一个数学错题'].map(p=><button key={p} onClick={()=>setMessage(p)}>{p}<ChevronRight size={13}/></button>)}</div>{!state.settings.ai.keyConfigured&&<Button variant="outline" onClick={()=>setPage('settings')}>配置学习 API <ArrowUpRight size={13}/></Button>}</div>:<>{state.chatMessages.slice(-30).map(m=><div className={`chat-message ${m.role}`} key={m.id}><span className="chat-avatar">{m.role==='assistant'?<Sparkles size={16}/>:'我'}</span><div><div className="chat-message-meta">{m.role==='assistant'?'学习助手':'我的问题'}{m.model&&<small>{m.model}</small>}</div><p>{m.content}</p>{m.role==='assistant'&&<div className="chat-message-actions"><button onClick={()=>{setSaveContent(m.content);setPlanEdit(null);setPlanOpen(true)}}><Save size={12}/>保存为学习计划</button>{m.tokens!=null&&<small>{compact(m.tokens)} 词元{m.cost!=null?` · 估算 ${money(m.cost,m.currency)}`:''}</small>}</div>}</div></div>)}{(sending||streamError)&&reply&&<div className="chat-message assistant streaming"><span className="chat-avatar"><Sparkles size={16}/></span><div><div className="chat-message-meta">{sending?'正在思考与生成…':'未完成的回答 · 未保存'}</div><p>{reply}</p></div></div>}{sending&&!reply&&<div className="chat-thinking"><Sparkles size={15}/><span>正在连接学习助手…</span></div>}<div ref={chatEnd}/></>}</div>{streamError&&<div className="form-error" role="alert">{streamError}</div>}{streamUsage&&<div className="helper-text">本次 {String(streamUsage.total_tokens??'未提供')} 词元{streamUsage.cost!=null?` · 按配置价格估算 ${money(Number(streamUsage.cost),String(streamUsage.currency??'CNY'))}`:''}</div>}<div className="chat-composer"><textarea aria-label="学习问题" rows={3} maxLength={12000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="描述你的问题，或粘贴需要分析的题目、英语作文…"/><div><span>AI 内容请结合教材核对 · 文本 API 不包含听力功能</span>{sending?<Button variant="outline" onClick={()=>abort.current?.abort()}><StopCircle size={14}/>停止</Button>:<Button disabled={!message.trim()||demo} onClick={()=>void send()}><Send size={14}/>发送</Button>}</div></div></Panel>}
 {tab==='mistakes'&&<Panel title="错题与复习" description="把错误整理成下一次进步的线索" action={<Button size="sm" onClick={()=>{setMistakeEdit(null);setMistakeOpen(true)}}><Plus size={14}/>新增错题</Button>}>{state.mistakes.length?<div className="mistake-list">{state.mistakes.map(m=><div className="mistake-card" key={m.id}><div><Badge variant="outline" className="badge-blue">{m.subject}</Badge><span className="record-actions"><EditButton onClick={()=>{setMistakeEdit(m);setMistakeOpen(true)}}/><DeleteButton collection="mistakes" id={m.id} name={m.question.slice(0,30)}/></span></div><h3>{m.question}</h3><details><summary>查看答案与复习备注</summary><p>{m.answer||'尚未填写答案'}</p>{m.notes&&<p className="muted">{m.notes}</p>}</details><small>下次复习：{m.nextReview?dateTime(m.nextReview):'尚未安排'}</small></div>)}</div>:<Empty icon={NotebookPen} title="让错题发挥真正的价值" description="记录题目、正确思路和错误原因，安排下一次复习。" onClick={()=>{setMistakeEdit(null);setMistakeOpen(true)}} action="记录第一道错题"/>}</Panel>}
 <RecordEditor open={goalOpen} onClose={()=>setGoalOpen(false)} collection="goals" title={goalEdit?'编辑学习目标':'设置学习目标'} fields={goalFields} record={goalEdit as unknown as Record<string,unknown>}/><RecordEditor open={planOpen} onClose={()=>setPlanOpen(false)} collection="studyPlans" title={planEdit?'编辑学习计划':'添加学习计划'} fields={planFields} record={planEdit as unknown as Record<string,unknown>} defaults={saveContent?{title:'AI 学习计划',subject:state.goals.find(g=>g.id===selectedGoal)?.subjects[0]??'学习',content:saveContent}:{}}/><RecordEditor open={mistakeOpen} onClose={()=>setMistakeOpen(false)} collection="mistakes" title={mistakeEdit?'编辑错题':'记录错题'} fields={mistakeFields} record={mistakeEdit as unknown as Record<string,unknown>}/>
 </div>
}
