import {useState} from 'react'
import {ListTodo,Plus,Clock,CheckCheck,CalendarDays,Upload,Info,ArrowUpRight} from 'lucide-react'
import {useWorkbench} from '../lib/store'
import {taskDueState,dateTime} from '../lib/domain'
import {buildTaskImport,compareTaskDueAt} from '../lib/task-import'
import type {Task} from '../lib/types'
import {Panel,Button,SectionTitle,Stat,Empty,TaskRow,RecordEditor,taskFields,Modal,Badge} from '../components/common'
export default function Tasks(){
 const {state,setPage,action,notify,demo}=useWorkbench(),[filter,setFilter]=useState('pending'),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[edit,setEdit]=useState<Task|null>(null),[importOpen,setImportOpen]=useState(false),[json,setJson]=useState(''),[error,setError]=useState(''),[importing,setImporting]=useState(false)
 if(!state)return null
 const pending=state.tasks.filter(t=>t.status==='pending'),overdue=pending.filter(t=>taskDueState(t)==='overdue'),soon=pending.filter(t=>taskDueState(t)==='soon'),completed=state.tasks.filter(t=>t.status==='completed')
 const tasks=state.tasks.filter(t=>(filter==='all'||filter==='pending'&&t.status==='pending'||filter==='completed'&&t.status==='completed'||filter==='overdue'&&taskDueState(t)==='overdue')&&(!query||(t.title+t.course).toLowerCase().includes(query.toLowerCase()))).sort(compareTaskDueAt)
 return <div className="page-enter"><SectionTitle eyebrow="ASSIGNMENTS & EXAMS" title="学习通任务" description="作业与考试，不再错过。按截止时间整理好每一件事。" action={<Button onClick={()=>{setEdit(null);setOpen(true)}}><Plus size={15}/>新增任务</Button>}/>
 <div className="stat-grid"><Stat label="未完成任务" value={pending.length} hint="按截止时间安排" icon={ListTodo}/><Stat label="24 小时内截止" value={soon.length} hint="优先处理" icon={Clock} tone="amber"/><Stat label="已逾期" value={overdue.length} hint="检查平台实际状态" icon={CalendarDays} tone="violet"/><Stat label="已完成" value={completed.length} hint="每一次完成都值得记录" icon={CheckCheck} tone="green"/></div>
 <div className="task-toolbar"><div className="segmented">{[{id:'pending',name:'待完成'},{id:'all',name:'全部'},{id:'overdue',name:'已逾期'},{id:'completed',name:'已完成'}].map(f=><button key={f.id} className={filter===f.id?'selected':''} onClick={()=>setFilter(f.id)}>{f.name}</button>)}</div><div className="toolbar-right"><input aria-label="搜索任务" className="compact-input" placeholder="搜索任务或课程" value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="outline" disabled={demo} onClick={()=>{setImportOpen(true);setJson('');setError('')}}><Upload size={14}/>导入 JSON</Button></div></div>
 <Panel title="任务清单" description={`${tasks.length} 项 · 截止时间以北京时间显示`}>{tasks.length?<div className="task-list full">{tasks.map(t=><TaskRow key={t.id} task={t} onEdit={()=>{setEdit(t);setOpen(true)}}/>)}</div>:<Empty icon={CheckCheck} title={query?'没有找到匹配任务':filter==='completed'?'完成后，记录会留在这里':'这里暂时没有待办'} description="可以手动新增任务，或导入整理后的学习通任务文件。" onClick={()=>{setEdit(null);setOpen(true)}} action="新增任务"/>}</Panel>
 <div className="two-columns task-notes"><Panel title="学习通接入状态" action={<Badge variant="outline" className="badge-amber">自动读取待验证</Badge>}><p className="body-copy">目前提供手动记录与任务文件导入。后续在真实登录会话下验证平台列表读取，确认可用后再启用自动同步。</p><div className="detail-row"><span>最近助手连接</span><strong>{dateTime(state.sync.lastSeen)}</strong></div><button className="text-button" onClick={()=>setPage('settings')}>查看同步助手设置 <ArrowUpRight size={13}/></button></Panel><Panel title="任务状态由你确认"><p className="body-copy">从列表中消失的任务不会自动标记完成。打开原平台链接后，请在学习通核对实际截止时间和提交状态。</p><div className="info-note"><Info size={14}/><span>相同平台任务 ID 会合并更新，导入失败不会删除已有任务。</span></div></Panel></div>
 <RecordEditor open={open} onClose={()=>setOpen(false)} collection="tasks" title={edit?'编辑学习任务':'新增学习任务'} fields={taskFields} record={edit as unknown as Record<string,unknown>} defaults={{source:edit?.source??'manual',...(edit?.platformId?{platformId:edit.platformId}:{})}}/>
 <Modal open={importOpen} onClose={()=>setImportOpen(false)} title="导入学习通任务" description="粘贴 JSON 或选择文件。按 platformId 合并，保留列表中没有出现的任务。"><label className="field"><span>选择 JSON 文件（最大 1 MB）</span><input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>1024*1024)throw new Error('文件不能超过 1 MB');setJson(await f.text());setError('')}catch(error){setError((error as Error).message)}}}/></label><label className="field import-json"><span>任务 JSON</span><textarea rows={8} value={json} onChange={e=>setJson(e.target.value)} placeholder={'{"tasks":[{"platformId":"work-42","title":"第三章习题","course":"高等数学","type":"assignment","dueAt":null,"status":"pending","url":""}]}'}/></label>{error&&<div className="form-error">{error}</div>}<div className="dialog-footer"><Button variant="outline" onClick={()=>setImportOpen(false)}>取消</Button><Button disabled={importing||!json||demo} onClick={async()=>{setImporting(true);setError('');try{const now=new Date().toISOString(),records=buildTaskImport(JSON.parse(json),state.tasks,now);const result=await action<{counts:Record<string,number>}>('/backup/restore',{backup:{version:1,exportedAt:now,records:{tasks:records}},mode:'merge'});notify(`已合并 ${result.counts.tasks??0} 项任务`);setImportOpen(false)}catch(e){setError((e as Error).message)}finally{setImporting(false)}}}>{importing?'正在导入…':'验证并导入'}</Button></div></Modal>
 </div>
}
