import {useEffect,useState,type ReactNode} from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import {Plus,X,ArrowUpRight,Database,LoaderCircle,Pencil,Trash2,Check,Clock,AlertCircle,CalendarDays,ExternalLink} from 'lucide-react'
import {Button} from './ui/button'
import {Card,CardContent,CardHeader,CardTitle,CardDescription} from './ui/card'
import {Badge} from './ui/badge'
import {useWorkbench} from '../lib/store'
import type {Collection,Task} from '../lib/types'
import {dateTime,taskDueState,dateKey,dateInputValue} from '../lib/domain'
export {Button,Card,CardContent,CardHeader,CardTitle,CardDescription,Badge}
export function Panel({title,description,action,children,className=''}:{title:ReactNode;description?:string;action?:ReactNode;children:ReactNode;className?:string}){return <Card className={`panel ${className}`}><CardHeader className="panel-head"><div><CardTitle>{title}</CardTitle>{description&&<CardDescription>{description}</CardDescription>}</div>{action}</CardHeader><CardContent>{children}</CardContent></Card>}
export function Empty({title,description,onClick,action='去配置',icon:Icon=Database}:{title:string;description:string;onClick?:()=>void;action?:string;icon?:typeof Database}){return <div className="empty"><span className="empty-icon"><Icon size={23}/></span><h3>{title}</h3><p>{description}</p>{onClick&&<Button size="sm" variant="outline" onClick={onClick}>{action}<ArrowUpRight size={14}/></Button>}</div>}
export function SectionTitle({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:ReactNode}){return <div className="section-title"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1><p>{description}</p></div>{action}</div>}
export function Stat({label,value,hint,icon:Icon,tone='blue'}:{label:string;value:ReactNode;hint:ReactNode;icon:typeof Clock;tone?:string}){return <Card className="stat"><CardContent><div className="stat-top"><span>{label}</span><span className={`icon-box ${tone}`}><Icon size={18}/></span></div><div className="stat-value">{value}</div><div className="stat-hint">{hint}</div></CardContent></Card>}
export function ActionButton({onClick,children,disabled=false}:{onClick:()=>void;children:ReactNode;disabled?:boolean}){return <Button disabled={disabled} onClick={onClick}><Plus size={16}/>{children}</Button>}
export function BusyButton({onClick,children,variant='outline'}:{onClick:()=>Promise<unknown>;children:ReactNode;variant?:'outline'|'default'|'ghost'}){const [busy,setBusy]=useState(false);const {notify}=useWorkbench();return <Button variant={variant} disabled={busy} onClick={async()=>{setBusy(true);try{await onClick()}catch(e){notify((e as Error).message,'error')}finally{setBusy(false)}}}>{busy&&<LoaderCircle className="spin" size={15}/>} {children}</Button>}
export function Modal({open,onClose,title,description,children}:{open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={v=>{if(!v)onClose()}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><Dialog.Title className="dialog-title">{title}</Dialog.Title><Dialog.Description className="dialog-description">{description??'填写后保存到你的个人工作台。'}</Dialog.Description><Dialog.Close className="dialog-close" aria-label="关闭"><X size={18}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export type Field={key:string;label:string;type?:'text'|'number'|'date'|'datetime-local'|'textarea'|'select'|'password';required?:boolean;placeholder?:string;options?:{value:string;label:string}[];default?:unknown;nullable?:boolean;min?:number;max?:number}
export function RecordEditor({open,onClose,collection,title,fields,record,defaults={}}:{open:boolean;onClose:()=>void;collection:Collection;title:string;fields:Field[];record?:Record<string,unknown>|null;defaults?:Record<string,unknown>}){
 const {save,notify,demo}=useWorkbench(),[values,setValues]=useState<Record<string,unknown>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(open){setError('');const initial={...defaults,...record};for(const f of fields){let v=initial[f.key]??f.default??'';if(f.type==='datetime-local'&&v){const d=new Date(String(v));v=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}if(f.type==='date'&&v)v=dateInputValue(String(v),f.key);if(Array.isArray(v))v=v.join('、');initial[f.key]=v}setValues(initial)}},[open,record])
 return <Modal open={open} onClose={onClose} title={title} description={demo?'当前为演示模式。退出演示后可创建、编辑和保存真实记录。':undefined}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const body:Record<string,unknown>={...defaults};for(const f of fields){let v=values[f.key];if(f.type==='number')v=v===''?null:Number(v);if(f.type==='datetime-local')v=v?new Date(String(v)).toISOString():null;if(f.type==='date'&&f.key==='targetDate')v=v?new Date(`${v}T00:00:00+08:00`).toISOString():null;if(f.key==='subjects')v=String(v??'').split(/[、,，]/).map(s=>s.trim()).filter(Boolean);if(f.nullable&&v==='')v=null;body[f.key]=v}await save(collection,body,record?.id as string|undefined);onClose()}catch(e){setError((e as Error).message);notify((e as Error).message,'error')}finally{setBusy(false)}}}><div className="form-grid">{fields.map(f=><label className={`field ${f.type==='textarea'?'wide':''}`} key={f.key}><span>{f.label}{f.required&&<i> *</i>}</span>{f.type==='select'?<select value={String(values[f.key]??'')} onChange={e=>setValues(previous=>({...previous,[f.key]:e.target.value}))} required={f.required}>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea rows={3} required={f.required} value={String(values[f.key]??'')} placeholder={f.placeholder} onChange={e=>setValues(previous=>({...previous,[f.key]:e.target.value}))}/>:<input onInput={f.type==='date'||f.type==='datetime-local'?e=>{const value=e.currentTarget.value;setValues(previous=>({...previous,[f.key]:value}))}:undefined} type={f.type??'text'} value={String(values[f.key]??'')} min={f.min} max={f.max} step={f.type==='number'?'any':undefined} required={f.required} placeholder={f.placeholder} onChange={e=>setValues(previous=>({...previous,[f.key]:e.target.value}))}/>}</label>)}</div>{error&&<div className="form-error"><AlertCircle size={15}/>{error}</div>}<div className="dialog-footer"><Button type="button" variant="outline" onClick={onClose}>取消</Button><Button type="submit" disabled={busy||demo}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}保存记录</Button></div></form></Modal>
}
export function DeleteButton({collection,id,name}:{collection:Collection;id:string;name:string}){const {remove,notify,demo}=useWorkbench();const [open,setOpen]=useState(false);return <><button className="icon-button danger" aria-label={`删除${name}`} onClick={()=>setOpen(true)} disabled={demo}><Trash2 size={16}/></button><Modal open={open} onClose={()=>setOpen(false)} title="删除这条记录？" description={`“${name}”将从工作台中删除。`}><div className="dialog-footer"><Button variant="outline" onClick={()=>setOpen(false)}>保留</Button><Button variant="destructive" onClick={async()=>{try{await remove(collection,id);setOpen(false)}catch(e){notify((e as Error).message,'error')}}}>删除</Button></div></Modal></>}
export function EditButton({onClick,label='编辑'}:{onClick:()=>void;label?:string}){return <button className="icon-button" aria-label={label} onClick={onClick}><Pencil size={15}/></button>}
export function Progress({value,tone='blue'}:{value:number|null;tone?:string}){return <div className={`progress-track ${tone}`} role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={value??undefined} aria-label="剩余百分比"><div style={{width:`${value??0}%`}}/></div>}
export function TaskRow({task,compact=false,onEdit}:{task:Task;compact?:boolean;onEdit?:()=>void}){
 const {save,notify,demo}=useWorkbench();const due=taskDueState(task);return <div className={`task-row ${task.status==='completed'?'completed':''}`}><button className={`task-check ${task.status==='completed'?'checked':''}`} disabled={demo} aria-label={`${task.status==='completed'?'恢复':'完成'}${task.title}`} onClick={async()=>{try{await save('tasks',{status:task.status==='completed'?'pending':'completed'},task.id)}catch(e){notify((e as Error).message,'error')}}}>{task.status==='completed'&&<Check size={14}/>}</button><div className="task-body"><strong>{task.title}</strong><span>{task.course||'未指定课程'} <span className="dot">·</span> {task.type==='exam'?'考试':task.type==='assignment'?'作业':'任务'}</span></div><div className="task-tail"><Badge className={due==='overdue'?'badge-red':due==='soon'?'badge-amber':'badge-muted'} variant="outline">{task.status==='completed'?'已完成':due==='overdue'?'已逾期':task.dueAt?dateTime(task.dueAt):'无截止时间'}</Badge>{!compact&&<><span className="record-actions">{task.url&&/^https?:\/\//.test(task.url)&&<a className="icon-button" href={task.url} target="_blank" rel="noreferrer" aria-label="前往学习通"><ExternalLink size={15}/></a>}{onEdit&&<EditButton onClick={onEdit}/>}<DeleteButton collection="tasks" id={task.id} name={task.title}/></span></>}</div></div>
}
export const taskFields:Field[]=[{key:'title',label:'任务名称',required:true,placeholder:'例如：高等数学第三章习题'},{key:'course',label:'课程',placeholder:'例如：高等数学'},{key:'type',label:'任务类型',type:'select',default:'assignment',options:[{value:'assignment',label:'作业'},{value:'exam',label:'考试'},{value:'other',label:'其他任务'}]},{key:'dueAt',label:'截止时间',type:'datetime-local',nullable:true},{key:'url',label:'原平台链接',placeholder:'https://'},{key:'status',label:'完成状态',type:'select',default:'pending',options:[{value:'pending',label:'未完成'},{value:'completed',label:'已完成'}]},{key:'note',label:'备注',type:'textarea'}]
export const planFields:Field[]=[{key:'title',label:'学习内容',required:true},{key:'subject',label:'科目',required:true},{key:'date',label:'计划日期',type:'date',default:dateKey(),required:true},{key:'minutes',label:'计划时长（分钟）',type:'number',default:30,min:1,required:true},{key:'status',label:'完成状态',type:'select',default:'pending',options:[{value:'pending',label:'待学习'},{value:'completed',label:'已完成'}]},{key:'content',label:'学习步骤',type:'textarea'}]
